# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - main
pr: none
variables:
  BuildConfiguration: 'release'
  ProductBinPath: '$(Build.SourcesDirectory)\src\Microsoft.Graph\bin\$(BuildConfiguration)'
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: 1es-windows-ps-compute-m
    sdl:
      git: # Customize checkout to enable longpaths in git for the paralled sdl https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/sourceanalysisstage
        longpaths: true
      baseline:
        baselineFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnbaselines
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnsuppress
      binskim: 
        enabled: false
        justificationForDisabling: 'Binskim is consistently crashing with error message : System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      jobs:
      - job: build
        timeoutInMinutes: 120
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: Microsoft.Graph.Beta.nupkg and release pipeline scripts'
            artifactName: ReadyForReleasePipeline
            targetPath: '$(Build.ArtifactStagingDirectory)'
        steps:
        - pwsh: git config --system core.longpaths true
          displayName: 'Enable long paths in git'
        - checkout: self
        - task: UseDotNet@2
          displayName: 'Use .NET 8.x sdk'
          inputs:
            packageType: sdk
            version: 8.x
        - task: UseDotNet@2
          displayName: 'Use .NET 6.x (for code signing tasks)'
          inputs:
            packageType: sdk
            version: 6.x
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: restore
            projects: '**/*.csproj'
        - task: PowerShell@2
          displayName: 'Validate updated version'
          condition: and(contains(variables['build.sourceBranch'], 'refs/heads/main'), succeeded())
          inputs:
            targetType: filePath
            filePath: '$(Build.SourcesDirectory)\scripts\ValidateUpdatedNugetVersion.ps1'
            arguments: '-packageName "Microsoft.Graph.Beta" -projectPath "$(Build.SourcesDirectory)\src\Microsoft.Graph\Microsoft.Graph.Beta.csproj"'
            pwsh: true
          enabled: true
        - powershell: |
            # This allows us to not have to checkin .csproj files with DelaySign and SignAssembly set to to true. If the flag is set,
            # then project is not debuggable with SignAssembly set to true.
            # Assumption: working directory is /src/
            $csprojPaths = @(".\Microsoft.Graph\Microsoft.Graph.Beta.csproj")
            foreach ($csprojPath in $csprojPaths) {
                $doc = New-Object System.Xml.XmlDocument
                $doc.Load($csprojPath)
                # Set the DelaySign element to 'true' so that delay signing is set.
                $delaySign = $doc.SelectSingleNode("//DelaySign");
                $delaySign.'#text'= "true"
                # Set the SignAssembly element to 'true' so that we can sign the assemblies.
                $signAssembly = $doc.SelectSingleNode("//SignAssembly");
                $signAssembly.'#text'= "true"
                $doc.Save($csprojPath);
            }
            Write-Host "Updated the .csproj files so that we can sign the built assemblies."
          workingDirectory: src
          displayName: 'Set project ready to sign'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build netstandard2.0'
          inputs:
            projects: '$(Build.SourcesDirectory)\src\Microsoft.Graph\Microsoft.Graph.Beta.csproj'
            arguments: '-c $(BuildConfiguration) --no-incremental -f netstandard2.0 --no-restore'
            
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build netstandard2.1'
          inputs:
            projects: '$(Build.SourcesDirectory)\src\Microsoft.Graph\Microsoft.Graph.Beta.csproj'
            arguments: '-c $(BuildConfiguration) --no-incremental -f netstandard2.1 --no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'dotnet build net5.0'
          inputs:
            projects: '$(Build.SourcesDirectory)\src\Microsoft.Graph\Microsoft.Graph.Beta.csproj'
            arguments: '-c $(BuildConfiguration) --no-incremental -f net5.0 --no-restore'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build test project'
          inputs:
            projects: '$(Build.SourcesDirectory)\tests\Microsoft.Graph.DotnetCore.Test\Microsoft.Graph.DotnetCore.Test.csproj'
            arguments: '-c $(BuildConfiguration) --no-incremental --no-restore'
        - task: DotNetCoreCLI@2
          displayName: 'run tests'
          inputs:
            command: 'test'
            arguments: '--configuration $(BuildConfiguration) --no-build --verbosity normal'
        - task: EsrpCodeSigning@5
          displayName: 'ESRP DLL Strong Name (Microsoft.Graph.Beta)'
          inputs:
            ConnectedServiceName: 'Federated DevX ESRP Managed Identity Connection'
            AppRegistrationClientId: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
            AppRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            AuthAKVName: 'akv-prod-eastus'
            AuthCertName: 'ReferenceLibraryPrivateCert'
            AuthSignCertName: 'ReferencePackagePublisherCertificate'
            FolderPath: src/Microsoft.Graph/bin/release
            Pattern: Microsoft.Graph.Beta.dll
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                  {
                      "keyCode": "CP-233863-SN",
                      "operationSetCode": "StrongNameSign",
                      "parameters": [],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  },
                  {
                      "keyCode": "CP-233863-SN",
                      "operationSetCode": "StrongNameVerify",
                      "parameters": [],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  }
              ]
            SessionTimeout: 20
            MaxConcurrency: 50
            MaxRetryAttempts: 5
            PendingAnalysisWaitTimeoutMinutes: 5
        - task: EsrpCodeSigning@5
          displayName: 'ESRP DLL CodeSigning (Microsoft.Graph.Beta)'
          inputs:
            ConnectedServiceName: 'Federated DevX ESRP Managed Identity Connection'
            AppRegistrationClientId: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
            AppRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            AuthAKVName: 'akv-prod-eastus'
            AuthCertName: 'ReferenceLibraryPrivateCert'
            AuthSignCertName: 'ReferencePackagePublisherCertificate'
            FolderPath: src/Microsoft.Graph/bin/release
            Pattern: Microsoft.Graph.Beta.dll
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                  {
                      "keyCode": "CP-230012",
                      "operationSetCode": "SigntoolSign",
                      "parameters": [
                          {
                              "parameterName": "OpusName",
                              "parameterValue": "Microsoft"
                          },
                          {
                              "parameterName": "OpusInfo",
                              "parameterValue": "http://www.microsoft.com"
                          },
                          {
                              "parameterName": "FileDigest",
                              "parameterValue": "/fd \"SHA256\""
                          },
                          {
                              "parameterName": "PageHash",
                              "parameterValue": "/NPH"
                          },
                          {
                              "parameterName": "TimeStamp",
                              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                          }
                      ],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  },
                  {
                      "keyCode": "CP-230012",
                      "operationSetCode": "SigntoolVerify",
                      "parameters": [],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  }
              ]
            SessionTimeout: 20
            MaxConcurrency: 50
            MaxRetryAttempts: 5
            PendingAnalysisWaitTimeoutMinutes: 5
        # arguments are not parsed in DotNetCoreCLI@2 task for `pack` command, that's why we have a custom pack command here
        - powershell: |
            dotnet pack $env:BUILD_SOURCESDIRECTORY/src/Microsoft.Graph/Microsoft.Graph.Beta.csproj /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg --no-build --output $env:BUILD_ARTIFACTSTAGINGDIRECTORY --configuration $env:BUILD_CONFIGURATION
          env:
            BUILD_CONFIGURATION: $(BuildConfiguration)
          displayName: 'dotnet pack'
        - task: EsrpCodeSigning@5
          displayName: 'ESRP NuGet CodeSigning'
          inputs:
            ConnectedServiceName: 'Federated DevX ESRP Managed Identity Connection'
            AppRegistrationClientId: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
            AppRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            AuthAKVName: 'akv-prod-eastus'
            AuthCertName: 'ReferenceLibraryPrivateCert'
            AuthSignCertName: 'ReferencePackagePublisherCertificate'
            FolderPath: '$(Build.ArtifactStagingDirectory)'
            Pattern: '*nupkg'
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                  {
                      "keyCode": "CP-401405",
                      "operationSetCode": "NuGetSign",
                      "parameters": [ ],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  },
                  {
                      "keyCode": "CP-401405",
                      "operationSetCode": "NuGetVerify",
                      "parameters": [ ],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  }
              ]
            SessionTimeout: 20
            MaxConcurrency: 50
            MaxRetryAttempts: 5
            PendingAnalysisWaitTimeoutMinutes: 5
        - task: CopyFiles@2
          displayName: 'Copy release scripts to artifact staging directory'
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: 'scripts\**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - stage: deploy
      condition: and(contains(variables['build.sourceBranch'], 'refs/heads/main'), succeeded())
      dependsOn: build
      jobs:
        - deployment: deploy_nuget
          templateContext:
            type: releaseJob
            isProduction: true
            inputs:
            - input: pipelineArtifact
              artifactName: ReadyForReleasePipeline
              targetPath: $(Pipeline.Workspace)
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            os: windows
            image: windows-latest
          dependsOn: []
          environment: nuget-org
          strategy:
            runOnce:
              deploy:
                steps:
                - task: NuGetToolInstaller@1
                  displayName: 'Use NuGet >=5.2.0'
                  inputs:
                    versionSpec: '>=5.2.0'
                    checkLatest: true
                - task: PowerShell@2
                  displayName: 'Get Latest Commit SHA from repo'
                  inputs:
                    targetType: filePath
                    filePath: '$(Pipeline.Workspace)\scripts\GetLatestCommitSHA.ps1'
                    arguments: '-repo "msgraph-beta-sdk-dotnet" -owner "microsoftgraph" -branchName "main"'
                    pwsh: true
                - task: PowerShell@2
                  displayName: 'Extract release information to pipeline'
                  inputs:
                    targetType: 'filePath'
                    filePath: $(Pipeline.Workspace)\scripts\GetNugetPackageVersion.ps1
                    pwsh: true
                    arguments: '-packageDirPath "$(Pipeline.Workspace)/"'
                - task: 1ES.PublishNuget@1
                  displayName: 'Push release to NuGet.org'
                  inputs:
                    command: push
                    packageParentPath: '$(Pipeline.Workspace)'
                    packagesToPush: '$(Pipeline.Workspace)\Microsoft.Graph.Beta.*.nupkg'
                    nuGetFeedType: external
                    publishFeedCredentials: 'microsoftgraph NuGet connection'
                - task: GitHubRelease@1
                  displayName: 'GitHub release (Upload Artifacts)'
                  inputs:
                    gitHubConnection: 'Kiota_Release'
                    target: $(Build.SourceVersion)
                    repositoryName: '$(Build.Repository.Name)'
                    action: edit
                    tag: $(VERSION_STRING)
                    addChangeLog: false
                    assetUploadMode: replace
                    assets: |
                      !**/**
                      $(Pipeline.Workspace)/Microsoft.Graph.Beta.*.*nupkg

